from dyno_v2.Module.BACmodbus import Parameter

# ASI controller read parameters
MB_BatteryVoltage = Parameter("Battery voltage", 265, 32, "V")
MB_MotorTemperature = Parameter("Motor temperature", 261, 1, "ºC")
MB_MotorCurrent = Parameter("Motor current", 262, 32, "A-peak")
MB_MotorRPM = Parameter("Motor RPM", 263, 1, "RPM")
MB_ControllerTemperature = Parameter("Controller temperature", 259, 1, "ºC")
MB_Brake1Volt = Parameter("Brake1 voltage", 271, 4096, "Volts")
MB_Brake2Volt = Parameter("Brake2 voltage", 272, 4096, "Volts")
MB_Warnings = Parameter("Warnings", 277, 1, "N/A")
MB_TorqueReference = Parameter("Torque Reference", 336, 4096, "pu")
MB_AutotuneRs = Parameter("Autotune Rs", 425, 1, "mOhms")
MB_AutotuneLs = Parameter("Autotune Ls", 426, 1, "uHenries")
MB_AutotuneHall0 = Parameter("Autotune Hall0", 440, 4096, "")
MB_AutotuneHall1 = Parameter("Autotune Hall1", 441, 4096, "")
MB_AutotuneHall2 = Parameter("Autotune Hall2", 442, 4096, "")
MB_AutotuneHall3 = Parameter("Autotune Hall3", 443, 4096, "")
MB_AutotuneHall4 = Parameter("Autotune Hall4", 444, 4096, "")
MB_AutotuneHall5 = Parameter("Autotune Hall5", 445, 4096, "")
MB_AutotuneHall6 = Parameter("Autotune Hall6", 446, 4096, "")
MB_AutotuneHall7 = Parameter("Autotune Hall7", 447, 4096, "")
MB_AutotuneRatedrpm = Parameter("Autotune Rated rpm", 462, 1, "rpm")
MB_AutotuneHallOffset = Parameter("Autotune hall offset angle", 460, 91.02222222, "degrees")
MB_RotorAngle = Parameter("Rotor angle", 278, 182.04444444444444444444444444444, "degrees")
MB_TripMeter = Parameter("Trip distance", 408, 100, "km")
MB_Faults = Parameter("Faults", 258, 1, "")
MB_MotorTemperatureFoldbackGain = Parameter("Motor temperature foldback gain", 320, 1, "")

MB_maxPA = Parameter("Max field weakening current", 129, 40.96, "%")
MB_ratedMotorPower = Parameter("Max electrical power", 73, 1, "W")
MB_ratedMotorSpeed = Parameter("Rated Motor Speed", 72, 1, "rpm")
MB_ratedMotorCurrent = Parameter("Rated Motor Speed", 71, 1, "A")
MB_tempFLDB = Parameter("Controller foldback start temperature", 35, 1, "ºC")

MB_dFeedbackAvg = Parameter("d feedback avg", 347, 4096, "pu")
MB_qFeedbackAvg = Parameter("q feedback avg", 348, 4096, "pu")
MB_dFeedback = Parameter("d feedback", 380, 4096, "pu")
MB_qFeedback = Parameter("q feedback", 381, 4096, "pu")

MB_Arms = Parameter("A rms", 433, 32, "Arms")
MB_Crms = Parameter("C rms", 434, 32, "Arms")

# ASI controller write parameters
MB_RemoteSpeed = Parameter("Remote speed", 490, 40.96, "RPM")
MB_MotorMaxCurrent = Parameter("Current Limit", 491, 40.96, "A")
MB_RemoteState = Parameter("Remote state command", 493, 1, "NA")
MB_RemoteThrottleV = Parameter("Remote throttle voltage", 495, 4096, "V")
MB_MotorDiscovery = Parameter("Motor discovery mode", 481, 1, "NA")
MB_Ls = Parameter("Ls", 74, 1, "uHenries")
MB_Rs = Parameter("Ls", 75, 1, "mOhms")
MB_Hall0 = Parameter("Hall0", 80, 1, "")
MB_Hall1 = Parameter("Hall1", 81, 1, "")
MB_Hall2 = Parameter("Hall2", 82, 1, "")
MB_Hall3 = Parameter("Hall3", 83, 1, "")
MB_Hall4 = Parameter("Hall4", 84, 1, "")
MB_Hall5 = Parameter("Hall5", 85, 1, "")
MB_Hall6 = Parameter("Hall6", 86, 1, "")
MB_Hall7 = Parameter("Hall7", 87, 1, "")
MB_HallOffset = Parameter("Hall offset angle", 79, 91.02222222, "degrees")
MB_FaultClear = Parameter("Clear faults", 508, 1, "")
MB_MotorFLDBstart = Parameter("Motor foldback start temperature", 91, 1, "ºC")
MB_MotorFLDBend = Parameter("Motor foldback end temperature", 92, 1, "ºC")
MB_MotorFLDBtrip = Parameter("Motor over temperature trip", 90, 1, "ºC")
MB_OpenLoopCurrent = Parameter("Open Loop Current", 483, 1, "A")
MB_OpenLoopFreq = Parameter("Open Loop Frequency", 484, 16, "Hz")
MB_TestMode = Parameter("tests Mode", 480, 1, "")

# ABB controller parameters
ABB_SAuto = Parameter("Start/Stop/Dir control", 1000, 1, "", [2], [7])
ABB_TAuto = Parameter("Start/Stop/Dir control", 1001, 1, "")
ABB_SvsT = Parameter("Direction", 1100, 1, "")
ABB_Tref = Parameter("Torque signal source", 1101, 1, "")
ABB_extSref = Parameter("External Speed signal source", 1102, 1, "")
ABB_extTref = Parameter("External Torque signal source", 1105, 1, "")
ABB_RunCMD = Parameter("Run command signal source", 1600, 1, "")
ABB_Ref2 = Parameter("Ref2 0-10000", 2, 1, "")
ABB_StatusWord = Parameter("Status word", 3, 1, "")
ABB_ctrlword = Parameter("Control Word", 0, 1, "")
ABB_faultOff = Parameter("Control Word", 3017, 1, "")
ABB_Direction = Parameter("Direction", 1002, 1, "")
ABB_FaultReset = Parameter("Fault Reset", 1603, 1, "")

# ABB controller parameter values for manual operatial (using the control pad)
ABB_SAuto.Add_Manual(2)
ABB_TAuto.Add_Manual(7)
ABB_SvsT.Add_Manual(2)
ABB_Tref.Add_Manual(8)
ABB_extSref.Add_Manual(2)
ABB_extTref.Add_Manual(3)
ABB_RunCMD.Add_Manual(1)
ABB_faultOff.Add_Manual(2)
ABB_Direction.Add_Manual(1)
ABB_FaultReset.Add_Manual(1)

# ABB controller parameter values for automatic operatial (control via PC)
ABB_SAuto.Add_AutoT(10)
ABB_TAuto.Add_AutoT(10)
ABB_SvsT.Add_AutoT(2)
ABB_Tref.Add_AutoT(8)
ABB_extSref.Add_AutoT(20)
ABB_extTref.Add_AutoT(20)
ABB_RunCMD.Add_AutoT(8)
ABB_faultOff.Add_AutoT(2)  # 2 for NO, 1 for fault
ABB_Direction.Add_AutoT(1)
ABB_FaultReset.Add_AutoT(8)
